apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "dragonfly.cdn.fullname" . }}
  namespace: {{ .Values.installation.namespace }}
  labels:
    app: {{ template "dragonfly.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  cdn.yaml: |-
    base:
      listenPort: {{ .Values.cdn.service.port }}
      downloadPort: {{ .Values.cdn.service.nginxPort }}
      systemReservedBandwidth: {{ .Values.cdn.config.base.systemReservedBandwidth }}
      maxBandwidth: {{ .Values.cdn.config.base.maxBandwidth }}
      enableProfiler: {{ .Values.cdn.config.base.enableProfiler }}
      failAccessInterval: {{ .Values.cdn.config.base.failAccessInterval }}
      gcInitialDelay: {{ .Values.cdn.config.base.gcInitialDelay }}
      gcMetaInterval: {{ .Values.cdn.config.base.gcMetaInterval }}
      gcStorageInterval: {{ .Values.cdn.config.base.gcStorageInterval }}
      taskExpireTime: {{ .Values.cdn.config.base.taskExpireTime }}
      storagePattern: {{ .Values.cdn.config.base.storagePattern }}
      console: {{ .Values.cdn.config.base.console }}
    plugins:
{{ toYaml .Values.cdn.config.plugins | indent 6 }}
  nginx.conf: |-
    worker_rlimit_nofile        100000;

    events {
        use                     epoll;
        worker_connections      20480;
    }

    http {
        include                 mime.types;
        default_type            application/octet-stream;
        root                    /home/admin/cai/htdocs;
        sendfile                on;
        tcp_nopush              on;

        server_tokens           off;
        keepalive_timeout       5;

        client_header_timeout   1m;
        send_timeout            1m;
        client_max_body_size    3m;

        index                   index.html index.htm;
        access_log              on;
        log_not_found           on;

        gzip                    on;
        gzip_http_version       1.0;
        gzip_comp_level         6;
        gzip_min_length         1024;
        gzip_proxied            any;
        gzip_vary               on;
        gzip_disable            msie6;
        gzip_buffers            96 8k;
        gzip_types              text/xml text/plain text/css application/javascript application/x-javascript application/rss+xml application/json;

        proxy_set_header        Host $host;
        proxy_set_header        X-Real-IP $remote_addr;
        proxy_set_header        Web-Server-Type nginx;
        proxy_set_header        WL-Proxy-Client-IP $remote_addr;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_redirect          off;
        proxy_buffers           128 8k;
        proxy_intercept_errors  on;

        server {
            listen              {{ .Values.cdn.service.nginxTargetPort }};
            location / {
              root {{ .Values.cdn.config.plugins.storage.config.baseDir }};
            }
        }
    }
