# scheduler 配置文件模版, 您可以根据您的需求更改这里的参数来配置您的 Scheduler

# scheduler 调度策略配置
scheduler:
  # abtest 是否开启ab测试
  # default: false
  abtest: false
  # aevaluator 指定当开启AB测试时，后缀为 _A 的 taskID 使用的 evaluator 计算方法
  # 只有当开启了 AB 测试的情况下该配置才生效
  # default: ""
  aevaluator: ""
  # bevaluator 指定当开启AB测试时，后缀为 _B 的 taskID 使用的 evaluator 计算方法
  # 只有当开启了 AB 测试的情况下该配置才生效
  # default: ""
  bevaluator: ""
  # workerNum 执行调度任务处理的 goroutine 数量
  # default: 默认机器可用的 CPU 数量
  workerNum: 12
  # backSourceCount 当 CDN 禁用或不可用时，回源客户端的数量
  # default: 3
  backSourceCount: 3
  # accessWindow 可触发 CDN 回源的时间间隔窗口
  # default: 3m
  accessWindow: 3m
  # candidateParentCount 候选父节点数量，
  # default: 10
  candidateParentCount: 10
  # scheduler 当前生效的 scheduler 调度策略
  # default: basic
  scheduler: basic
  # cdnLoad CDN 节点可以提供上传的最大负载
  # default: 100
  cdnLoad: 100
  # clientLoad 普通客户端节点可以提供上传的最大负载
  # default: 10
  clientLoad: 10
  # openMonitor 是否打开监控，目前只监控了当前的 peer 列表状态信息
  # default: false
  openMonitor: false
  # gc 元数据回收策略
  gc:
    # peerGCInterval peer 的回收间隔
    peerGCInterval: 1m
    # peerTTL peer 的离开时间, 距离上次 peer 的访问时间超过改值则 peer 会被设置成 leave 状态
    peerTTL: 10m
    # peerTTI peer 的 TTI 时间，距离上次 peer 的访问时间超过改值则 peer 会被设置成 zombie 状态
    peerTTI: 3m
    # taskGCInterval task 的回收间隔
    taskGCInterval: 1m
    # taskTTL task 的离开时间, 距离上次 task 的访问时间超过改值则 task 会被设置成 leave 状态
    taskTTL: 10m
    # taskTTI 的 TTI 时间，距离上次 task 的访问时间超过改值则 task 会被设置成 zombie 状态
    taskTTI: 3m

# server scheduler 服务实例配置信息
server:
  # ip
  # ip: 127.0.0.1
  # host
  # host: localhost
  # ListenPort is the ip and port scheduler server listens on.
  # default: 8002
  port:

# 动态数据配置
dynConfig:
  # type 动态数据来源类型
  type: manager

# manager 配置
manager:
  # addr manager 访问地址
  addr: ""
  # schedulerClusterID 要注册的 scheduler 集群 ID
  schedulerClusterID:
  # keepAlive 和 manager 保持心跳的配置
  keepAlive:
    # interval 保持心跳的时间间隔
    interval: 5s

# scheduler 自身主机信息
host:
  # location scheduler 实例所在的地理位置信息
  location: ""
  # idc scheduler 实例所在机房
  idc: ""

# machinery 异步任务配置，配置参考 https://github.com/RichardKnop/machinery
job:
  # globalWorkerNum
  globalWorkerNum: 2
  # schedulerWorkerNum
  schedulerWorkerNum: 3
  # localWorkerNum
  localWorkerNum: 3
  # redis configuration
  redis:
    # host redis 服务实例地址
    host: "redis"
    # port redis 服务实例端口
    port: 6379
    # password
    password: ""
    # brokerDB
    brokerDB: ""
    # backendDB
    backendDB: ""

# disableCDN 是否停用 CDN
# default: false
disableCDN: false

# Console 是否在控制台程序中显示日志
# default: false
console: false

# verbose 是否使用调试级别的日志、是否启用 pprof。
# default: false
verbose: false

# pprofPort pprof 监听的端口，仅在 verbose 为 true 时可用
# default is -1. If it is 0, pprof will use a random port.
pprofPort: -1

# jaeger 地址
# 默认使用空字符串（不配置 jaeger）
jaeger: ""

# tracer 中使用的 service-name
# 默认值：dragonfly-cdn
service-name: dragonfly-scheduler
