apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "dragonfly.scheduler.fullname" . }}
  labels:
    app: {{ template "dragonfly.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  scheduler.yaml: |-
    deubug: {{ .Values.scheduler.config.debug }}
    server:
      port: {{ .Values.scheduler.containerPort }}
    worker:
{{ toYaml .Values.scheduler.config.worker | indent 6 }}
    {{- if .Values.scheduler.config.staticCDN }}
    dynconfig:
      cdnDirPath: /opt/dragonfly/scheduler-cdn
    {{- end}}

---

{{- if .Values.scheduler.config.staticCDN }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: scheduler-static-cdn
{{- end}}
