namespace: dragonfly-system
resources:
- ../../bases
images:
- name: dragonflyoss/cdn
  newName: sample.com/d7y/cdn
  newTag: latest
- name: dragonflyoss/dfget
  newName: sample.com/d7y/dfget
  newTag: latest
- name: dragonflyoss/scheduler
  newName: sample.com/d7y/scheduler
  newTag: latest
